### ISSUE TITLE
npm dev won't run

### ISSUE THREAD

**Issue by gabrielkunkel** [Foxandxss/GermanWords-ng1-webpack#2]
This is pretty cool but it's not running right for me. Testing seems to work great with this one though

**Error on running dev**

> germanwords-ng1-webpack@1.0.0 dev /Users/gabrielkunkel/WebstormProjects/angular-es6-webpack-demo
> webpack-dev-server --history-api-fallback --inline --progress

  0% compile 10% 0/1 build modules 70% 1/1 build modules 40% 1/2 build modulesevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:99:10)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! germanwords-ng1-webpack@1.0.0 dev: `webpack-dev-server --history-api-fallback --inline --progress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the germanwords-ng1-webpack@1.0.0 dev script 'webpack-dev-server --history-api-fallback --inline --progress'.
npm ERR! This is most likely a problem with the germanwords-ng1-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --history-api-fallback --inline --progress
npm ERR! You can get their info via:
npm ERR!     npm owner ls germanwords-ng1-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gabrielkunkel/WebstormProjects/angular-es6-webpack-demo/npm-debug.log

Process finished with exit code 1

**Comment by Foxandxss** [comment]
This sounds to be like you were trying to run this server at the same time you had another one open (likely the workflow on my other repo).

`EADDRINUSE` means that the port 8080 (in this case) was in use.

I will take the opportunity to update the deps in here too.
